### ISSUE TITLE
Can’t build this from source

### ISSUE THREAD

**Issue by chris-morgan** [CartoType/CartoType-Public#1]
I’m trying to build this from source, and failing.

1. Check out CartoType-Public repository, look around, observe .pro files and so try running qmake and then Make in src/apps/Maps:

```console
user@host ~$ git clone https://github.com/CartoType/CartoType-Public
user@host ~$ cd CartoType-Public/src/apps/Maps
user@host ~/CartoType-Public/src/apps/Maps$ qmake
Info: creating stash file /home/user/CartoType-Public/src/apps/Maps/.qmake.stash
user@host ~/CartoType-Public/src/apps/Maps$ make
make: *** No rule to make target '/home/user/CartoType-Public/src/apps/Maps/../../main/platform/qt/CartoTypeQtMapRenderer/build64/release/libCartoTypeQtMapRenderer.a', needed by 'CartoTypeMaps'.  Stop.
```

2. OK, so I guess we need to build CartoTypeQtMapRenderer first:

```console
user@host ~/CartoType-Public/src/apps/Maps$ cd ../../main/platform/qt/CartoTypeQtMapRenderer
user@host ~/CartoType-Public/src/main/platform/qt/CartoTypeQtMapRenderer$ qmake
Info: creating stash file /path/to/CartoType-Public/src/main/platform/qt/CartoTypeQtMapRenderer/.qmake.stash
WARNING: Failure to find: ../../../graphics/cartotype_opengl_es_render.cpp
WARNING: Failure to find: ../../../library/libtess2/bucketalloc.c
WARNING: Failure to find: ../../../library/libtess2/dict.c
WARNING: Failure to find: ../../../library/libtess2/geom.c
WARNING: Failure to find: ../../../library/libtess2/mesh.c
WARNING: Failure to find: ../../../library/libtess2/priorityq.c
WARNING: Failure to find: ../../../library/libtess2/sweep.c
WARNING: Failure to find: ../../../library/libtess2/tess.c
```

3. Uh oh, failed to find some of the things needed. Can’t get cartotype_opengl_es_render.cpp, but libtess2 I can find:

```console
user@host ~/CartoType-Public/src/main/platform/qt/CartoTypeQtMapRenderer$ cd ../../../library
user@host ~/CartoType-Public/src/main/platform/qt/CartoTypeQtMapRenderer$ git clone https://github.com/memononen/libtess2 ../../../../../../libtess2
user@host ~/CartoType-Public/src/main/platform/qt/CartoTypeQtMapRenderer$ ln -s ../../../../libtess2/Source ../../../library/libtess2
user@host ~/CartoType-Public/src/main/platform/qt/CartoTypeQtMapRenderer$ qmake
WARNING: Failure to find: ../../../graphics/cartotype_opengl_es_render.cpp
```

4. Well, slightly better, I guess. It says “warning”, what happens if I try building without it?

```console
user@host ~/CartoType-Public/src/main/platform/qt/CartoTypeQtMapRenderer$ make
g++ -c -pipe -O2 -fPIC -std=gnu++1y -Wall -Wextra -D_REENTRANT -DCARTOTYPE_FOR_QT -DNDEBUG -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../../base -I../../../framework -I../../../graphics -I../../../mapdata -I../../../svg -I../../../xml -I../../../library/libtess2 -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o cartotype_qt_map_renderer.o cartotype_qt_map_renderer.cpp
cartotype_qt_map_renderer.cpp:9:10: fatal error: cartotype_vector_tile.h: No such file or directory
    9 | #include "cartotype_vector_tile.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:825: cartotype_qt_map_renderer.o] Error 1
```

5. OK, seems I’m stuck, there’s no cartotype_vector_tile.h anywhere.

Maybe this is deliberate, but I file this issue in the hope that it’s not. 🙂

**Comment by GrahamAsher** [comment]
Thanks for the report. I'll look into it and get back to you later today. The libraries libcartotype.a and libCartoTypeQtMapRenderer.a, and the other things to do with OpenGL graphics, ought to be available in the evaluation SDK, but I can see from the latest version that they are not.

**Comment by GrahamAsher** [comment]
The libraries libcartotype.a and libCartoTypeQtMapRenderer.a are now supplied as part of the evaluation SDK. To build and run the Linux version of the Maps App please do the following:

- clone this repository into CartoType-Public
- open CartoType-Public/src/apps/Maps/Maps.pro in Qt Creator
- configure the Maps.pro project to use Desktop Qt GCC 64bit
- select the Release build
- download the latest [CartoType Linux evaluation SDK](https://www.cartotype.com/developers/evaluation-sdks)
- unzip the CartoType Linux evaluation SDK
- copy the file cartotype-linux-sdk/bin/libCartoTypeQtMapRenderer.a into a new folder CartoType-Public/src/main/platform/qt/CartoTypeQtMapRenderer/build64/release/
- copy the file libcartotype.a into a new folder CartoType-Public/src/main/single_library/unix/bin/ReleaseLicensed
- build the Maps project; it should compile and run successfully
