### ISSUE TITLE
Remove text this is an unlicensed copy for evaluation use only

### ISSUE THREAD

**Issue by NguyenDinhTrong99** [CartoType/CartoType-Public#1]
Hi team,

The library help me solve my problem. So, can u tell me how to remove text, i try download app sample window. It load amazing and beautiful. If i can, how much i will pay. I use it load map offiline when my app haven't network. I so hope.

Thanks for team!

**Comment by GrahamAsher** [comment]
Our license pricing is available at https://www.cartotype.com/products/pricing.
